### ISSUE TITLE
USER STORY: Book a class

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#16]
As a **signed in User ** I can **book a class** so that **participate in the yoga class**.

## Acceptance Criteria:
- Acceptance Criteria1: There must be a form with classes options;
- Acceptance Criteria2: The form has to be close to the classes calendar so that the user can easily relate to the classes days/dates;
- Acceptance Criteria3: If the reservation is not successful, the user must be notified;
- Acceptance Criteria4: If the reservation is successful redirect the user to a reservation list.

## Tasks:
- [ ] Task 1: Create a form model for reservations;
- [ ] Task 2: Develop a book function that handles invalid reservations, such as the class has no more available space, the class is no longer available since older than today, and you already booked this class;
- [ ] Task 3: A successful outcome of the reservation should redirect the user to a reservations page.
