### ISSUE TITLE
USER STORY: Delete reservation

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#17]
As a **signed in User** I can **delete a reservation* so that **I can change my mind about participating in the yoga class**

## Acceptance Criteria:
- Acceptance Criteria1: Next to the reservation, there must be a delete option;
- Acceptance Criteria2: Display a confirm message before deletion;
- Acceptance Criteria3: The available spaces of the class must be updated.

## Tasks:
- [ ] Task 1: Create a delete button next to the reservation;
- [ ] Task 2: Create a modal to confirm or discharge deletion;
- [ ] Task 3: Develop a function that increases the number of the class's available spaces in case of deletion.
