### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#19]
As a **signed in User** I can **add  a note to a reservation* so that **I can have a reminder for the reserved class**

## Acceptance Criteria:
- Acceptance Criteria1: The note is close to the reservation it refers to;
- Acceptance Criteria2: Display the note form in the same page of the reservations;
- Acceptance Criteria 3: The user can add

## Tasks:
- [ ] Task 1: Create a calendar table  with days columns and time slots rows;
- [ ] Task 2: The calendar days row should automatically update to have always displayed the current week and the next;
- [ ] Task 3: Using JavaScript allocate published classes in the correct calendar cell.
