### ISSUE TITLE
USER STORY: Manage notes

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#20]
As a **signed in User** I can **edit and delete my notes** so that **I can update  their content or delete if unnecessary**

## Acceptance Criteria:
- Acceptance Criteria1: Display edit and delete buttons next to each note;
- Acceptance Criteria2: The edit button should redirect the user to a prepopulated form that should update the note when submitted;
- Acceptance Criteria3: The delete button should display a modal to request the deletion confirmation, and delete the note if deletion is confirmed.

## Tasks:
- [ ] Task 1: Develop  a delete note view;
- [ ] Task 2: Develop  an  edit view that renders a template containing an edit note form and handles its authentication;
- [ ] Task 3: In the reservations template add a modal to request deletion confirmation.
