### ISSUE TITLE
USER STORY: Create a draft yoga type

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#22]
As a **Site Admin** I can **create draft yoga type** so that **I can finish writing the content later**

## Acceptance Criteria:
- Acceptance Criteria1: Display a yoga type section in the admin panel;
- Acceptance Criteria2: Allow the admin to publish  yoga types or leave them as drafts by updating the status.

## Tasks:
- [ ] Task 1: Create a model for  yoga types;
- [ ] Task 2: The model for the  yoga type should have a status field to determine if a  post is a draft or published
- [ ] Task 3: In admin.py, the  yoga type class should have the status in the list display.
