### ISSUE TITLE
USER STORY: Create a draft yoga class

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#23]
As a **Site Admin** I can **create draft yoga class** so that **I can finish writing the content later**

## Acceptance Criteria:
- Acceptance Criteria1: Display a yoga class section in the admin panel;
- Acceptance Criteria2: Allow the admin to publish  yoga classes or leave them as drafts by updating the status.

## Tasks:
- [ ] Task 1: Create a model for  yoga classes;
- [ ] Task 2: The model for the  yoga class should have a status field to determine if a yoga class is a draft or published
- [ ] Task 3: In admin.py, the  yoga class class should have the status in the list display.
