### ISSUE TITLE
USER STORY: Manage yoga types

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#24]
As a **site Admin** I can **create, read, update and delete yoga types** so that **I can manage my their page content and create yoga classes related to them**

## Acceptance Criteria:
- Acceptance Criteria1: Create yoga types through the admin panel;
- Acceptance Criteria 2: Allow the admin to update yoga types;
- Acceptance Criteria 2: Allow the admin to delete yoga types.

## Tasks:
- [ ] Task 1: Create a model for yoga types;
- [ ] Task 2: Yoga types should be YogaClass ForeignKey;
- [ ] Task 3: In admin.py create a class for yoga types;
