### ISSUE TITLE
USER STORY: Manage yoga classes

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#25]
As a **site Admin** I can **create, read, update and delete yoga classes** so that **I can publish them according to my availability**

## Acceptance Criteria:
- Acceptance Criteria1: Create yoga classes through the admin panel;
- Acceptance Criteria 2: Allow the admin to update yoga classes;
- Acceptance Criteria 2: Allow the admin to delete yoga classes.

## Tasks:
- [ ] Task 1: Create a model for yoga classes;
- [ ] Task 2: In the model, yoga type should be a ForeignKey;
- [ ] Task 3: In admin.py create a class for yoga classes;
