### ISSUE TITLE
USER STORY: View yoga types

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/power-yoga#26]
As a **signed in site User** I can **view the types of yoga practiced in the classes** so that **I can decide which one suits me best**

## Acceptance Criteria:
- Acceptance Criteria1: Create yoga types list;
- Acceptance Criteria2: When clicked on a yoga type, display its description;

## Tasks:
- [ ] Task 1: Create a classes template;
- [ ] Task 2: Develop a view that passes the classes to the template;
- [ ] Task 3: The view should render the template.
